var nelements_radio=14;
var nomform_radio="fnom01";
var possibilitats_radio=2;
 
var correccio_radio = new Array(nelements_radio);
correccio_radio[0] = "1";
correccio_radio[1] = "2";
correccio_radio[2] = "1";
correccio_radio[3] = "2";
correccio_radio[4] = "2";
correccio_radio[5] = "1";
correccio_radio[6] = "2";
correccio_radio[7] = "1";
correccio_radio[8] = "1";
correccio_radio[9] = "2";
correccio_radio[10] = "2";
correccio_radio[11] = "1";
correccio_radio[12] = "1";
correccio_radio[13] = "2";