var nelements=14;
var nomform="fnom02";
var nelements_desp=4;

var correccio = new Array(nelements);
correccio[0] = "1";
correccio[1] = "2";
correccio[2] = "1";
correccio[3] = "2";
correccio[4] = "1";
correccio[5] = "1";
correccio[6] = "2";
correccio[7] = "2";
correccio[8] = "3";
correccio[9] = "3";
correccio[10] = "1";
correccio[11] = "1";
correccio[12] = "3";
correccio[13] = "2";